sudo: required
services:
  - docker
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

env:
  - ORPC_TEST_VERSION=8.0"
  - ORPC_TEST_VERSION=9.0"
  - ORPC_TEST_VERSION=10.0"

before_install:
  - docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.4
  - docker run -d -p 8069:8069 --name odoo --link db:db -t "odoo:$ORPC_TEST_VERSION"

install:
  # OdooRPC dependencies
  - pip install sphinx

script:
  - python -m unittest discover -v
  - PYTHONPATH=.:$PYTHONPATH sphinx-build -b doctest -d doc/build/doctrees doc/source build/doctest
